# Generated by Django 5.0.3 on 2024-05-29 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('data', models.DateTimeField()),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('titulo', models.CharField(default='', max_length=255)),
                ('data_criacao', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('tempo_preparo', models.CharField(max_length=255, null=True)),
                ('imagem_principal', models.FileField(max_length=255, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DenunciaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unidadeMedida', models.CharField(max_length=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ingrediente')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.receita')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('path', models.FileField(upload_to='')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.receita')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.receita'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('userDjango', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='BanUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('data', models.DateTimeField()),
                ('justificativa', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='BanReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('data', models.DateTimeField()),
                ('justificativa', models.TextField()),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.receita')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='BanImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('data', models.DateTimeField()),
                ('justificativa', models.TextField()),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.imagem')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='BanComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('data', models.DateTimeField()),
                ('justificativa', models.TextField()),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.comentario')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario')),
            ],
        ),
    ]
