# Generated by Django 5.0.3 on 2024-03-20 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='idUsuario',
            new_name='usuario',
        ),
        migrations.CreateModel(
            name='BanReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('data', models.DateTimeField()),
                ('justificativa', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.administrador')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.receita')),
            ],
        ),
        migrations.CreateModel(
            name='BanUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('data', models.DateTimeField()),
                ('justificativa', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.administrador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('data', models.DateTimeField()),
                ('texto', models.TextField()),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.receita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='BanComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('data', models.DateTimeField()),
                ('justificativa', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.administrador')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=20)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.equipamento')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.receita')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('path', models.CharField()),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.receita')),
            ],
        ),
        migrations.CreateModel(
            name='BanImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('data', models.DateTimeField()),
                ('justificativa', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.administrador')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.imagem')),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unidadeMedida', models.CharField(max_length=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ingrediente')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.receita')),
            ],
        ),
    ]
