# Generated by Django 5.0.3 on 2024-04-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_userdjango'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='tempo_preparo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
