# Generated by Django 5.0.3 on 2024-04-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_receita_tempo_preparo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='imagem_principal',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='path',
            field=models.FileField(upload_to=''),
        ),
    ]
