# Generated by Django 5.0.3 on 2024-04-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_receita_imagem_principal_alter_imagem_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
