# Generated by Django 5.0.3 on 2024-05-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_equipamentoreceita_equipamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cnpj',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.CharField(null=True),
        ),
    ]
