# Generated by Django 5.0.3 on 2024-06-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usuario_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dataAniversario',
            field=models.DateTimeField(null=True),
        ),
    ]
