# Generated by Django 5.0.3 on 2024-05-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usuario_cnpj_usuario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dataDescobrimentoBrasil',
            field=models.DateField(null=True),
        ),
    ]
