# Generated by Django 5.0.3 on 2024-05-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usuario_is_admin_denunciacomentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
