# Generated by Django 5.0.3 on 2024-05-23 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usuario_is_admin'),
        ('core', '0009_remove_usuario_empresa'),
    ]

    operations = [
    ]
