# Generated by Django 5.0.3 on 2024-05-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usuario_datadescobrimentobrasil'),
        ('core', '0010_merge_20240522_2154'),
    ]

    operations = [
    ]
