# Generated by Django 5.0.3 on 2024-05-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_usuario_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
