# Generated by Django 5.0.3 on 2024-06-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usuario_dataaniversario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='instagram',
            new_name='texto',
        ),
    ]
