# Generated by Django 5.0.3 on 2024-06-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_receita_custo_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='origem',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
