# Generated by Django 5.0.3 on 2024-06-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_instagram_usuario_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='texto',
            new_name='instagram',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='dataAniversario',
        ),
    ]
