# Generated by Django 5.0.3 on 2024-05-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_usuario_cnpj_and_more'),
    ]

    operations = [

    ]
