# Generated by Django 5.0.3 on 2024-06-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_texto_usuario_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_aniversario',
            field=models.DateTimeField(null=True),
        ),
    ]
