# Generated by Django 5.0.3 on 2024-05-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usuario_cnpj_usuario_datadescobrimentobrasil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='salarioMinimo',
        ),
    ]
